<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTIN480255" failures="2" tests="4" name="Test" time="2.126" errors="0" timestamp="2025-06-16T10:30:23 IST">
  <testcase classname="testCasae.OtherTest" name="forgetPassword" time="2.022">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method testCasae.OtherTest.forgetPassword() didn&amp;apos;t finish within the time-out 2000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method testCasae.OtherTest.forgetPassword() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at testCasae.OtherTest.forgetPassword(OtherTest.java:26)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 6 stack frames]]>
    </failure>
  </testcase> <!-- forgetPassword -->
  <testcase classname="testCasae.OtherTest" name="login" time="0.008">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: 
at testCasae.OtherTest.login(OtherTest.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="testCasae.OtherTest" name="getParameters" time="0.003"/>
  <testcase classname="testCasae.OtherTest" name="logout" time="0.001">
    <skipped/>
  </testcase> <!-- logout -->
</testsuite> <!-- Test -->
